<a href="/posts">Посты</a>
<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>
<!-- BEGIN (write your solution here) -->
<form action="/posts/<?= htmlspecialchars($post['id']) ?>" method="post">
<input type="hidden" name="_METHOD" value="PATCH">
  <?php require '_form.phtml' ?>
  <input type="submit" value="Update">
</form>
<!-- END -->
