<?php error_reporting(E_ALL);
ini_set('display_errors', 'On');
?>
<?php if (count($flash) > 0) : ?>
  <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
          <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
  </ul>
<?php endif ?>

<!-- BEGIN (write your solution here) -->
<?php if (!$currentUser) : ?>
    <form action="/session" method="post">
  <div>
    <label>
        Имя
    <input type="email" required name="user[email]" value="">
    </label>
  </div>
    <input type="submit" value="Sign In">
</form>

<?php else : ?>
  <ul>
    <li><?= htmlspecialchars($currentUser)?></li>
    <li><a href="/users">Список пользователей</a></li>
    <li><a href="/users/new">Создать нового пользователя</a></li>
  </ul>
  <form action="/session" method="post">
  <input type="hidden" name="_METHOD" value="DELETE">
    <input type="submit" value="Sign Out">
</form>
<?php endif ?>
<!-- END -->
