<?php if (count($flash) > 0) : ?>
  <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
          <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
  </ul>
<?php endif ?>
<div>
  <ul>
    <?php foreach ($users as $user) : ?>
    <li><b>Name:</b> <?= htmlspecialchars($user['name']) ?> <b>Email:</b> <?= htmlspecialchars($user['email']) ?> 
    <b>Id:</b> <a href="users/<?= htmlspecialchars($user['id']) ?>"><?= htmlspecialchars($user['id']) ?></a></li>
    <?php endforeach ?>
  </ul>
</div>